# Android CI Workflow
#
# This GitHub Actions workflow builds and runs unit tests for the Android project
# whenever code is pushed to or a pull request is opened against the `master` branch.
#
# You can adjust the behavior by modifying this file.

name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew  # Ensure the Gradle wrapper is executable (required on Unix-based systems)

      - name: Run unit tests
        run: ./gradlew test
