name: Labeling Commands

on:
  issues:
    types: [closed]
    
  issue_comment:
  
  pull_request:
  
permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write # to generate status
  checks: write # to generate status
  
jobs:
  labeler:
    name: Label Issue/PR
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-path: .github/labeler.yml   
  remove_labels:
    name: Remove Labels on Close
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'Lifecycle: Active, Lifecycle: Frozen'
