name: Labeling Commands

on:  
  issues:
    types: [opened]
    
  issue_comment:
  
  pull_request:
  
permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  labeler:
    name: Label Issue/PR
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-path: .github/labeler.yml
      - uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const issue_number = context.issue.number;
            const labels = ['Lifecycle: Active'];
            await github.issues.addLabels({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            });
