name: Labeling Commands

on:  
  issues:
    types: [opened]
  issue_comment:
  pull_request:
  
permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  labeler:
    name: Label Issue/PR
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-path: .github/labeler.yml
