name: Labeling Commands

on:
  issue_comment:
  
  pull_request:
  
permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write # to generate status
  checks: write # to generate status
  
jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-path: .github/labeler.yml
